-- TODO: map these to spritesheet
-- ENTITY_IDS = {
--     ['characters'] = {1, 2, 3, 4, 5}
-- }

-- ENTITY_DEFS = {
--     ['knight'] = {
--         frame = 1,
--         textures = 'wizard'
--     },
--     ['king'] = {
--         frame = 2,
--         textures = 'wizard'
--     }
-- }

-- ENTITY_DEFS = {
--   ['player'] = {
--       animations = {
--           ['idle-down'] = {
--               frames = {3},
--               texture = 'wizards'
--           },
--           ['idle-up'] = {
--               frames = {2},
--               texture = 'wizards'
--           },
--       }
--   },
--   ['enemy'] = {
--       animations = {
--           ['idle-down'] = {
--               frames = {2},
--               texture = 'wizards'
--           },
--           ['idle-up'] = {
--               frames = {1},
--               texture = 'wizards'
--           },
--       }
--   }
-- }